### ISSUE TITLE
适配pg数据库，创建配置并添加标签保存报错

### ISSUE THREAD

**Issue by qhyjoe** [wuchubuzai2018/nacos-multidatasource#1]
适配pg数据库，创建配置并添加标签保存报错，原因是`config_tags_relation`表中nid字段在为空导致，mysql中nid字段是自增字段，pg似乎不支持这种自增

**Comment by wuchubuzai2018** [comment]
感谢测试，那个脚本的那个表的sql换成这个：
DROP TABLE IF EXISTS "config_tags_relation";
CREATE TABLE "config_tags_relation" (
  "id" bigserial NOT NULL,
  "tag_name" varchar(128)  NOT NULL,
  "tag_type" varchar(64) ,
  "data_id" varchar(255)  NOT NULL,
  "group_id" varchar(128)  NOT NULL,
  "tenant_id" varchar(128) ,
  "nid" bigserial NOT NULL
)

nid改成bigserial这个类型的

**Comment by wuchubuzai2018** [comment]
最新的脚本已提交更新：
https://github.com/wuchubuzai2018/nacos-multidatasource/blob/main/%E6%96%B9%E6%A1%88%E4%B8%80%E5%AE%9E%E7%8E%B0%E4%BB%A3%E7%A0%81/nacos210/distribution/conf/nacos-pg.sql
