### ISSUE TITLE
dm8的COMPATIBLE_MODE=2时 导入/新增配置后列表为空，但数据表已存在数据

### ISSUE THREAD

**Issue by qinchz** [wuchubuzai2018/nacos-multidatasource#3]
因为之前有从oracle迁移数据到达梦，因此设置了达梦的COMPATIBLE_MODE=2（兼容oracle），使用nacos210启动正常，但配置列表始终为空。新增/导入配置均可以在CONFIG_INFO表看到数据，但界面上为空。  
我特意使用COMPATIBLE_MODE=0测试是没有这个问题的。希望大佬有空可以看下2的情况，谢谢

**Comment by qinchz** [comment]
spring.datasource.platform 配置的是mysql，改为oracle就可以了

**Comment by wuchubuzai2018** [comment]
> 因为之前有从oracle迁移数据到达梦，因此设置了达梦的COMPATIBLE_MODE=2（兼容oracle），使用nacos210启动正常，但配置列表始终为空。新增/导入配置均可以在CONFIG_INFO表看到数据，但界面上为空。 我特意使用COMPATIBLE_MODE=0测试是没有这个问题的。希望大佬有空可以看下2的情况，谢谢

出现这个情况可能是默认public没存储到数据库中造成的，
可以调试代码看看，我的达梦方言是默认是继承oracle方言的，oracle的逻辑基本上就是将默认的public存储到数据库中，保存完成后，界面查询不出来，可能就是默认方言问题

**Comment by qinchz** [comment]
> > 因为之前有从oracle迁移数据到达梦，因此设置了达梦的COMPATIBLE_MODE=2（兼容oracle），使用nacos210启动正常，但配置列表始终为空。新增/导入配置均可以在CONFIG_INFO表看到数据，但界面上为空。 我特意使用COMPATIBLE_MODE=0测试是没有这个问题的。希望大佬有空可以看下2的情况，谢谢
> 
> 出现这个情况可能是默认public没存储到数据库中造成的， 可以调试代码看看，我的达梦方言是默认是继承oracle方言的，oracle的逻辑基本上就是将默认的public存储到数据库中，保存完成后，界面查询不出来，可能就是默认方言问题

谢谢，我调试之后发现的使用的方言是mysql才意识到问题。因为是直接起的源码，console里的platform没有配置正确，打扰了。
