### ISSUE TITLE
新增nacos配置总是报发布失败。请检查参数是否正确。

### ISSUE THREAD

**Issue by farmer97** [wuchubuzai2018/nacos-multidatasource#4]
看日志发现字段非空约束问题nested exception is org.postgresql.util.PSQLException: ERROR: null value in column "encrypted_data_key" violates not-null constraint，请问是我哪里配置不对吗？
![image](https://user-images.githubusercontent.com/104909225/201041724-96847532-617d-4f30-be23-88c16f5987ae.png)
![image](https://user-images.githubusercontent.com/104909225/201041796-18646b59-a10f-412a-bec8-b8ff4ffc8dbd.png)

**Comment by wuchubuzai2018** [comment]
估计可能是低版本的Postgresql吧，这样你把这几张表的字段encrypted_data_key设置为可以为空的状态，默认程序会插入一个字符串，我看看把脚本默认为空给他改一下吧

**Comment by farmer97** [comment]
应该是数据库的问题，我这边用的是国产数据库vastbase，驱动连接用的是postgresql，但数据类型大多与Oracle兼容，导致空字符串入库后直接为null

**Comment by farmer97** [comment]
应该是数据库的问题，我这边用的是国产数据库vastbase，驱动连接用的是postgresql，但数据类型大多与Oracle兼容，导致空字符串入库后直接为null
